language: node_js
node_js: 10
cache: yarn

script:
  - yarn lint
  - yarn stylelint
  - yarn electron:build
  - yarn webpack:build
  - yarn dist --all

notifications:
  email: false

before_install:
  - yarn --frozen-lockfile
  - ./install-wine.sh

sudo: required
