language: node_js
node_js: 10
os:
  - windows
  - linux
  - osx
cache: yarn

script:
  - yarn build
  - yarn package --executable-name=prettycom-$TRAVIS_OS_NAME-x64

before_install:
  - yarn --frozen-lockfile

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: prettycom-$TRAVIS_OS_NAME-x64
  skip_cleanup: true
  draft: true

notifications:
  email: false
