language: node_js
node_js: 10
os:
#  - windows
  - linux
  - osx

script:
  - yarn build
  - yarn package --executable-name prettycom-"$TRAVIS_OS_NAME"-x64

before_install:
  - yarn --frozen-lockfile

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: Release/prettycom-"$TRAVIS_OS_NAME"-x64
  skip_cleanup: true
  draft: true
  on:
    branch: travis3

notifications:
  email: false
